// front_react/src/components/Header.js
import React from 'react';
import {Link, useNavigate} from "react-router-dom";
import Alert from "./Alert";
import {actions} from "../store/slices";
import {AUTH_MODULE, EQUIPMENT_MODULE} from "../store/const";
import {useDispatch} from "react-redux";

const Header = () => {

  const dispatch = useDispatch()
  const navigate = useNavigate()
  const fetchLogout = actions[AUTH_MODULE.POST_AUTH_LOGOUT_ACTION]

  const handleLogout = async () => {
    await dispatch(fetchLogout())
    navigate('/')
  }
  return (
      <header>
        <div className="wrapper">
          <nav className="navbar navbar-light bg-light">
            <form className="container-fluid justify-content-end">
              <Link to="/search" className="btn btn-outline-primary me-2" type="button">
                Поиск
              </Link>
              <Link to="/equipment" className="btn btn-outline-primary me-2" type="button">
                Добавить
              </Link>
              <button className="btn btn-outline-primary me-2" type="button" onClick={handleLogout}>
                Выход
              </button>
            </form>
          </nav>
          <Alert/>
        </div>
      </header>
  );
};

export default Header;

// front/src/components/Header.vue
<template>
  <header>
    <div class="wrapper">
      <nav class="navbar navbar-light bg-light">
        <form class="container-fluid justify-content-end">
          <RouterLink to="/" class="btn btn-outline-primary me-2" type="button">
            Поиск
          </RouterLink>
          <RouterLink to="/equipment" class="btn btn-outline-primary me-2" type="button">
            Добавить
          </RouterLink>
          <button class="btn btn-outline-primary me-2" type="button" v-on:click="handleLogout">
            Выход
          </button>
        </form>
      </nav>
      <Alert />
    </div>
  </header>
</template>

<script>
import Alert from "./Alert.vue";
import {AUTH_MODULE} from '@/stores/const'
import {mapActions} from "vuex";
export default {
  name: "Header",
  components: {Alert},
  methods: {
    ...mapActions({
      fetchLogout: AUTH_MODULE.FETCH_LOGOUT,
    }),
    async handleLogout() {
      await this.fetchLogout()
      await this.$router.push('/login')
    }
  },
}
</script>

<style scoped>

</style>
